Controllers/AdressesController.cs
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using Todo_Asp_Mvc.Net.Data;
using Todo_Asp_Mvc.Net.Models;

namespace Todo_Asp_Mvc.Net.Controllers
{
    [HandleError]
    public class AdressesController : Controller
    {
        private Todo_Asp_MvcNetContext db = new Todo_Asp_MvcNetContext();

        // GET: Adresses
        public ActionResult Index()
        {
            return View(db.Adresses.ToList());
        }

        // GET: Adresses/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Adresse adresse = db.Adresses.Find(id);
            if (adresse == null)
            {
                return HttpNotFound();
            }
            return View(adresse);
        }

        // GET: Adresses/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Adresses/Create
        // Pour vous protéger des attaques par survalidation, activez les propriétés spécifiques auxquelles vous souhaitez vous lier. Pour 
        // plus de détails, consultez https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Name,Rue,Angle,CreatedAt,UpdatedAt")] Adresse adresse)
        {
            if (ModelState.IsValid)
            {
                db.Adresses.Add(adresse);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(adresse);
        }

        // GET: Adresses/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Adresse adresse = db.Adresses.Find(id);
            if (adresse == null)
            {
                return HttpNotFound();
            }
            return View(adresse);
        }

        // POST: Adresses/Edit/5
        // Pour vous protéger des attaques par survalidation, activez les propriétés spécifiques auxquelles vous souhaitez vous lier. Pour 
        // plus de détails, consultez https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name,Rue,Angle,CreatedAt,UpdatedAt")] Adresse adresse)
        {
            if (ModelState.IsValid)
            {
                db.Entry(adresse).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(adresse);
        }

        // GET: Adresses/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Adresse adresse = db.Adresses.Find(id);
            if (adresse == null)
            {
                return HttpNotFound();
            }
            return View(adresse);
        }

        // POST: Adresses/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Adresse adresse = db.Adresses.Find(id);
            db.Adresses.Remove(adresse);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Controllers/PersonController.cs
using System;
using System.Web.Mvc;
using Todo_Asp_Mvc.Net.Data;
using Todo_Asp_Mvc.Net.Models;
using Todo_Asp_Mvc.Net.Repositories;
using Todo_Asp_Mvc.Net.Services;

namespace Todo_Asp_Mvc.Net.Controllers
{
    [HandleError]
    public class PersonController : Controller
    {
        private IRepositoryPerson _repositoryPerson =  new RepositoryPerson(new Todo_Asp_MvcNetContext());
        private IRepositoryAdresse _repoAdresse = new RepositoryAdresse(new Todo_Asp_MvcNetContext());
        private Messagerie  messagerie = new Messagerie();

        // GET: Person
        public ActionResult Index(int page =1, int pageSize =10)
        {
            var _countTotal = _repositoryPerson.CountTotal();
            Metadata _metadata = new Metadata
            {
                HasNext = _countTotal > (pageSize * page),
                HasPrev = page != 1,
                CurrentPage = page,
                PageSize = pageSize,
                PrevPage = (page > 1) ? (page - 1) : 1,
                NextPage = page + 1,
                TotalPages = _countTotal / pageSize
            };
            ViewBag.Title = "Liste persons";
            ViewBag.CountTotal = _countTotal;
            ViewBag.Metadata = _metadata;
            var result = _repositoryPerson.GetAll(page, pageSize);
            return View(result);
        }
        // create a person
        [HttpGet]
        public ActionResult Create()
        {
            ViewBag.Title = "Creation Personne";
            ViewBag.Adresses = _repoAdresse.GetAll();
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Nom,Prenom,DateNaissance,AdresseId")] Person item)
        {
            if (ModelState.IsValid)
            {
            _repositoryPerson.Create(item);
            this.Flash("Création d'une personne avec succès.",FlashLevel.Success);
            return RedirectToAction("Index");
            }
            this.Flash("Verifier les entrées .", FlashLevel.Danger);
            ViewBag.Adresses = _repoAdresse.GetAll();
            return View(item);
        }
        public ActionResult Show(int id)
        {
            ViewBag.Title = "Affichage d'une personne";
            var result = _repositoryPerson.GetOne(id);
            return View(result);
        }
        public ActionResult Delete(int id)
        {
            var result = _repositoryPerson.Delete(id);
            if(result == true)
            {
                this.Flash("La suppression a été un succès.",FlashLevel.Success);
                return RedirectToAction("Index");
            }
            this.Flash("Erreur de suppression. Réessayer",FlashLevel.Danger);
            return RedirectToAction("Index");
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Update(Person itemUpdated)
        {
            _repositoryPerson.Update(itemUpdated);
            this.Flash("La modification a été un succès.", FlashLevel.Success);
            return RedirectToAction("Index");
        }
        [HttpGet]
        public ActionResult Edit(int id)
        {
            ViewBag.Title = "Modification d'une personne";
            ViewBag.Adresses = _repoAdresse.GetAll();
            var result = _repositoryPerson.GetOne(id);
            return View(result);
        }
        public void Export()
        {
            var list = _repositoryPerson.GetAll(1,1000);
            var csv = String.Format("Nom;Prenom;Date de Naissance;Adresse;Date de création;Date de modification");
            // datas to share
            foreach(var item in list)
            {
                csv += "\r\n";
                csv += String.Format(" {0};{1};{2};{3};{4};{5};",
                    item.Nom,item.Prenom,
                    ShortDate((DateTime)item.DateNaissance),
                    $"{item.Adresse.Angle} {item.Adresse.Rue}  {item.Adresse.Name}",
                    ShortDate((DateTime)item.CreatedAt),
                    ShortDate((DateTime)item.UpdatedAt)
                    );
            }
            Response.Clear();
            Response.Buffer = true;
            Response.AddHeader("content-disposition", $"attachment;filename=Liste_Personnes_{DateTime.UtcNow.ToShortDateString()}.csv");
            Response.Charset = "utf-8";
            Response.ContentType = "application/text";
            Response.Output.Write(csv);
            Response.Flush();
            Response.End();
        }

        public ActionResult SendEmail()
        {
            return View();
        }
        [HttpPost]
        public ActionResult SendEmail(int id,[Bind(Include = "Titre,Message")] MessageEmail item)
        {
            messagerie.SendEmail(item);
            return View();
        }
        public ActionResult ExportPdf()
        {
            return RedirectToAction("Index");
        }

        protected string ShortDate(DateTime date)
        {
            return date.ToShortDateString();
        }
    }
}

Views/Shared/_Flash.cshtml
@helper FlashMessage(System.Web.Mvc.TempDataDictionary tempData)
{
    <div class="flash-messages">
        @foreach (FlashLevel level in (FlashLevel[])Enum.GetValues(typeof(FlashLevel)))
        {
            string type = level.ToString().ToLower();
            string key = "flash-" + type;

            if (tempData.ContainsKey(key))
            {
                IList<string> messages = (IList<string>)tempData[key];

                foreach (string message in messages)
                {
                        <p class="alert m-2 alert-@type" role="alert">@message</p>
                }
            }
        }
    </div>
}
@FlashMessage(TempData)

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Todo</title>
    <link href="~/lib/font-awesome/css/all.min.css" rel="stylesheet">
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container flex justify-content-between">
            <div class="navbar-header ">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Todo App", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("List Person", "Index", "Person")</li>
                    <li>@Html.ActionLink("List Adresses", "Index", "Adresses")</li>
                </ul>
            </div>
        </div>
    </div>
<div class="container body-content">
    @Html.Partial("_Flash")
    @RenderBody()
    <hr/>
    <footer>
        <p>&copy; @DateTime.Now.Year - Todo</p>
    </footer>
</div>
    <script src="~/lib/font-awesome/js/all.min.js"></script>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>